version: '1'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: CMS_DB
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
